// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_dp
NumericVector C_dp(NumericVector x, double lam);
RcppExport SEXP _dpcc_C_dp(SEXP xSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(C_dp(x, lam));
    return rcpp_result_gen;
END_RCPP
}
// C_paint
NumericMatrix C_paint(NumericVector x, NumericVector lambda);
RcppExport SEXP _dpcc_C_paint(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(C_paint(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// find_lambda_c
double find_lambda_c(NumericMatrix X);
RcppExport SEXP _dpcc_find_lambda_c(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(find_lambda_c(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dpcc_C_dp", (DL_FUNC) &_dpcc_C_dp, 2},
    {"_dpcc_C_paint", (DL_FUNC) &_dpcc_C_paint, 2},
    {"_dpcc_find_lambda_c", (DL_FUNC) &_dpcc_find_lambda_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dpcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
