# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_dp <- function(x, lam) {
    .Call('_dpcc_C_dp', PACKAGE = 'dpcc', x, lam)
}

C_paint <- function(x, lambda) {
    .Call('_dpcc_C_paint', PACKAGE = 'dpcc', x, lambda)
}

find_lambda_c <- function(X) {
    .Call('_dpcc_find_lambda_c', PACKAGE = 'dpcc', X)
}

